#!/bin/bash

echo "=== Checking Teads Native Setup ==="
echo ""

echo "1. Checking if TeadsSDK pod is installed:"
if [ -d "ios/Pods/TeadsSDK" ]; then
    echo "✅ TeadsSDK pod exists"
    ls -1 ios/Pods/TeadsSDK/Frameworks/
else
    echo "❌ TeadsSDK pod NOT found"
fi
echo ""

echo "2. Checking teads-react-native native files:"
if [ -f "node_modules/teads-react-native/ios/RCTTeadsAdPlacementMedia.mm" ]; then
    echo "✅ RCTTeadsAdPlacementMedia.mm exists"
else
    echo "❌ RCTTeadsAdPlacementMedia.mm NOT found"
fi

if [ -f "node_modules/teads-react-native/ios/TeadsAdContainer.swift" ]; then
    echo "✅ TeadsAdContainer.swift exists"
else
    echo "❌ TeadsAdContainer.swift NOT found"
fi
echo ""

echo "3. Checking generated codegen files:"
if [ -d "node_modules/teads-react-native/ios/generated/RNTeadsReactNativeViewSpec" ]; then
    echo "✅ Codegen spec files exist"
    echo "   Files:"
    ls -1 node_modules/teads-react-native/ios/generated/RNTeadsReactNativeViewSpec/ | head -5
else
    echo "❌ Codegen spec files NOT found"
fi
echo ""

echo "4. Checking if Swift bridging header would be generated:"
echo "   Looking for Swift files in teads-react-native..."
find node_modules/teads-react-native/ios -name "*.swift" -type f | head -3
echo ""

echo "5. Checking Xcode build folder for generated files:"
if [ -d "ios/build" ]; then
    echo "✅ ios/build exists"
    if [ -f "ios/build/generated/ios/TeadsReactNative-Swift.h" ]; then
        echo "✅ TeadsReactNative-Swift.h was generated"
    else
        echo "⚠️  TeadsReactNative-Swift.h NOT found in build output"
        echo "   This file is auto-generated by Xcode when building Swift code"
    fi
else
    echo "⚠️  ios/build folder doesn't exist (project not built yet?)"
fi
echo ""

echo "6. Checking pod list for teads:"
cd ios
POD_LIST=$(pod list 2>/dev/null | grep -i teads || echo "")
cd ..
if [ -n "$POD_LIST" ]; then
    echo "✅ Teads pods found:"
    echo "$POD_LIST"
else
    echo "⚠️  No Teads pods found in pod list"
fi
echo ""

echo "=== IMPORTANT NEXT STEPS ==="
echo ""
echo "In Xcode, please check:"
echo "1. Press Cmd+9 to open Report Navigator"
echo "2. Select the latest build"
echo "3. Search for 'error' or 'TeadsReactNative-Swift.h'"
echo "4. Look for any Swift compilation errors"
echo "5. Check if 'TeadsReactNative-Swift.h' was generated"
echo ""
echo "The native Swift code is likely NOT being compiled or linked."
echo "This is why you see no logs in Xcode console."
