# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'TestProject' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Workaround: fmt 11 consteval is broken with Xcode 26 (Apple Clang 17+).
    # base.h unconditionally redefines FMT_USE_CONSTEVAL so we must patch the source.
    base_h = File.join(installer.sandbox.root, 'fmt/include/fmt/base.h')
    if File.exist?(base_h)
      File.chmod(0644, base_h)
      content = File.read(base_h)
      old_line = '#elif defined(__apple_build_version__) && __apple_build_version__ < 14000029L'
      new_line = "#elif defined(__apple_build_version__) && __apple_build_version__ >= 17000000L\n#  define FMT_USE_CONSTEVAL 0  // consteval is broken in Apple clang 17+ (Xcode 26).\n#{old_line}"
      content = content.gsub(old_line, new_line)
      File.write(base_h, content)
    end
  end
end
